### ISSUE TITLE
Schraubenlöcher fehlen

### ISSUE THREAD

**Issue by koefmatt** [openlab-aux/sphincter2-cad#1]
Im großen Zahnrad fehlen die Schraubenlöcher, sodass man die kleine Platte, die das Zahnrad halten soll, nicht an der Grundplatte festschrauben kann.

**Comment by michiwend** [comment]
das ist nicht korrekt. Der Schlitz endet in beiden Seiten in den Schraubenlöchern. Wenn man das zahnrad verdreht, erreicht man so die schrauben.
